# Encoding fix for Windows: set via PYTHONIOENCODING environment variable
# Run pytest with: PYTHONIOENCODING=utf-8 python -m pytest ...
# or simply: set PYTHONIOENCODING=utf-8 && python -m pytest ...
# This conftest.py is intentionally minimal to avoid conflicts with pytest capture.
pass
